#Образ (Os) + платформа .NET 
FROM mcr.microsoft.com/dotnet/aspnet:8.0 As base

EXPOSE 80
ENV ASPNETCORE_URLS http://+:80
ENV ASPNETCORE_ENVIRONMENT Development

WORKDIR /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0 As build

WORKDIR /src

COPY ["SocNet1/SocNet1.csproj", "SocNet1.csproj/"]
COPY ["BuisnessLogic/BusinessLogic.csproj", "BusinessLogic.csproj/"]
COPY ["BuisnessLogic.Tests/BuisnessLogic.Tests.csproj", "BuisnessLogic.Tests.csproj/"]
COPY ["Domain/Domain.csproj", "Domain.csproj/"]
COPY ["DataAccess/DataAccess.csproj", "DataAccess.csproj/"]
RUN dotnet restore "BuisnessLogic.Tests.csproj"

COPY . .
FROM build AS publish
RUN dotnet publish "BusinessLogic.Tests/BusinessLogic.Tests.csproj" -c Release -o /app/publish /p:UseAppHost=false

COPY --from=publish /app/publish .

ENTRYPOINT [ "dotnet", "BuisnessLogic.Tests.dll" ]
