
services:
  SocNet1:
    image: ${DOCKER_REGISTRY-}socnet1
    build: 
      context: .
      dockerfile: ./Dockerfile 
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=db;Database=MyTest;User=DESKTOP-SRKQPQK\Дан;Integrated Security=true;MultipleActiveResultSets=true
      - Server=sql.bsite.net\MSSQL2016;Database=danilas111_;User Id=danilas111_;Password=comp123)(f;TrustServerCertificate=true;
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Comp123)(f"
      - "ACCEPT_EULA=Y"
    container_name: mssql

    #C:\Users\Дан\Documents\GitHub\API\src