name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'
    - name: Find SocNet1.sln
      run: |
        find . -name "SocNet1.sln"
    - name: Build
      run: dotnet build ./src/SocNet1/SocNet1.sln --configuration Release
    - name: Test
      run: dotnet test ./src/SocNet1/SocNet1.sln --configuration Release --no-build