name: .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore C:/Users/Дан/Documents/GitHub/API/src/SocNet1.sln

    - name: Build
      run: dotnet build C:/Users/Дан/Documents/GitHub/API/src/SocNet1.sln --no-restore

    - name: Test
      run: dotnet test C:/Users/Дан/Documents/GitHub/API/src/SocNet1.sln --no-build --verbosity normal